/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.*;
import org.apache.commons.cli.Option;

import java.io.PrintWriter;


public class App {
    private static final Option BATCH = new Option("b", "batch", true, "batch file containing expressions to evaluate");
    private static final Option HELP = new Option("h", "help", false, "print usage message");
    private static final Option OUTPUT = new Option("o", "output", true, "output file");

    private static void printHelp(Options options){
        HelpFormatter formatter = new HelpFormatter();
        PrintWriter pw = new PrintWriter(System.out);
        formatter.printHelp("eval",options);
        formatter.printUsage(pw, 100,"");
        //formatter.printOptions(pw, 100, options, 2,5);
        pw.close();
    }
    public static void main(String[] args) {
        CommandLineParser parser = new DefaultParser();
        // create Options object
        Options options = new Options();

        // add b option
        options.addOption(BATCH);

        // add h option
        options.addOption(HELP);

        // add o option
        options.addOption(OUTPUT);



        //String[] block = new String[]{ "--block-size=10" };

        try {
            CommandLine cl =  parser.parse(options, args);


            if(cl.hasOption("b")){
                String clientId = cl.getOptionValue("b");
                System.out.println(clientId);

            }else if(cl.hasOption("o")){
                String clientId = cl.getOptionValue("o");
                System.out.println(clientId);

            }else{
                printHelp(options);
            }
        }
        catch (ParseException exp) {
            System.out.println("Unexpected exception:" + exp.getMessage());
        }
    }
}
